# The URL the site will be built for
base_url = "https://quantike.xyz"

title = "quantike"
description = "Thoughts on systems and software"
default_language = "en"
theme = "serene"
output_dir = "public"
minify_html = false # Keep this false, as it may cause issues with some styles
generate_feeds = true # Whether to generate a feed file in root, read docs for more info about rss feed
feed_filenames = ["atom.xml"] # "feed.xml" | "atom.xml" | "rss.xml", read docs for more info
taxonomies = [{ name = "tags" }, { name = "categories" }]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[markdown.highlighting]
style = "class"
light_theme = "Gruvbox Light"
dark_theme = "Gruvbox Dark"
extra_themes = [
  "themes/serene/highlight_themes/gruvbox-light.json",
  "themes/serene/highlight_themes/gruvbox-dark.json"
]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
# Put all your custom variables here
sections = [
    { name = "posts", path = "/posts", is_external = false },
    { name = "tidbits", path = "/tidbits", is_external = false },
    { name = "projects", path = "/projects", is_external = false},
    { name = "stack", path = "/stack", is_external = false },
    { name = "now", path = "/now", is_external = false },
    { name = "about", path = "/about", is_external = false },
    # { name = "tags", path = "/tags", is_external = false },
    # { name = "github", path = "https://github.com/<your-username>", is_external = true },
]
blog_section_path = "/posts"

back_link_text = "Back" # Text of the back button
force_theme = false # false | "light" | "dark"

footer_copyright = "© 2025 quantike"
footer_credits = true # Whether to show "Built with zola and serene" in footer

not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"

reaction = false # Whether to enable anonymous emoji reactions (Note: You need to set up a working api endpoint to enable this feature)
reaction_align = "right" # "left" | "center" | "right"
reaction_endpoint = "https://example.com/api/reaction"
